ignore all the chrome warnings
see:
/home/runner/work/atlas-ui/atlas-ui/src/background.ts
TypeScript error in /home/runner/work/atlas-ui/atlas-ui/src/background.ts(4,22):
Property 'chrome' does not exist on type 'Window'.  TS2339

    2 | export {}
    3 | // When running this project as a web app and not as a Chrome extension, we have to manually set the chrome environment variable
  > 4 | const chrome: Window["chrome"] = window.chrome || {};
      |                      ^
    5 | chrome.runtime.onMessage.addListener((message: RequestMessage) => {
    6 |     console.log("Message received in background.js!", message);
    7 | });
.ts(4,22):
Property 'chrome' does not exist on type 'Window'.  TS2339